### ISSUE TITLE
command T searches files that are ignored in our .gitignore

### ISSUE THREAD

**Issue by wildtype** [KMK-ONLINE/vim-config#2]
this slows down fuzzy finding of search.  when i command t it finds things in /tmp and /node_modules, both of which are ignored in my .gitignore

**Comment by rustyworks** [comment]
For CtrlP, this issue is already fix in [this](https://github.com/KMK-ONLINE/vim-config/blob/master/.vim/common_config/01_plugin_config.vim#L42)

For fzf, add this to bashrc
export FZF_DEFAULT_COMMAND='ag -g ""'
