### ISSUE TITLE
command-t.vim could not load the C extension

### ISSUE THREAD

**Issue by walamsyah** [KMK-ONLINE/vim-config#6]
Found this error on Ubuntu 16.04 LTS with Ruby 2.3.1-p112 and Vim Ruby version: 2.3.1-p112
Ruby installed from RVM

**Comment by walamsyah** [comment]
Found the solution. Follow these steps:
1. `rvm use system`
2. `cd ~/.vim/plugged/command-t/ruby/command-t/`
3. `ruby extconf.rb`
4. `make clean`
5. `make`

**Comment by enangyusup** [comment]
Owh... thanks pek.
